### GET TOKEN --- SET HOST
< {%
    client.global.set("host", "https://api-orchestration-protocole-enquete.developpement.insee.fr/");
    client.global.set("host", "http://localhost:8080/");
%}
POST https://auth.insee.test/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("auth_token", response.body.access_token);
    client.global.set("processDefinitionKey", "tst");
    client.global.set("businessKey", "AAA");
    //Set the context file in the last query
%}

###Create process

POST {{host}}/protools-process/create_process_instance_with_context?processDefinitionId={{processDefinitionKey}}&businessKey={{businessKey}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="contexte.json"

< bpmnAndContext/creation_context_platine/collecte_web_no_comm.json
