### GET TOKEN
< {%
    client.global.set("host", "https://api-orchestration-protocole-enquete.developpement.insee.fr/");
    client.global.set("host", "http://localhost:8080/");
%}
POST https://auth.insee.test/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
  client.global.set("auth_token", response.body.access_token);
  client.log("TOKEN = "+client.global.get("auth_token"));
    client.log("RESPONSE = "+client.global);
%}


#######envoi BPMN
POST {{host}}/repository/deployments?deploymentKey=test_deploymentKey&deploymentName=test_deploymentName
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testDeploy.bpmn20.xml"

< ./bpmnAndContext/simpleProcess.bpmn20.xml

--WebAppBoundary--

> {%
    client.log("Hello");
    client.global.set("deploymentId", response.body.id);
    client.log("deploymentId = "+client.global.get("deploymentId"));
%}

#######vérif de ce que contient le déployment
GET {{host}}/repository/deployments/{{deploymentId}}/resources
Authorization: Bearer {{auth_token}}
accept: */*

