### GET TOKEN
POST https://auth.insee.test/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("auth_token", response.body.access_token);
    client.log("TOKEN = "+client.global.get("auth_token"));
    client.log("RESPONSE = "+client.global);
%}

### MISE à jour mot de passe utilisateur B28CKCJ

POST https://api.gestion-comptes-utilisateurs.recette.insee.fr/realms/questionnaire-particuliers/users/FXMPES55/init-password?
    change-password-reset-status=false
accept: application/json
X-SUGOI-ASYNCHRONOUS-ALLOWED-REQUEST: false
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "password": "Metallic@123"
}