### GET TOKEN
POST https://auth.insee.test/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
  client.global.set("auth_token", response.body.access_token);
  client.log("TOKEN = "+client.global.get("auth_token"));
    client.log("RESPONSE = "+client.global);


      client.global.set("CAMPAGNE_ID", "AAA2022X02");
%}


###Create SU on sabiane questionnaire
POST https://api.questionnaire-enqueteurs.enquetes.recette2.insee.fr/api/campaign/{{CAMPAGNE_ID}}/survey-unit
Content-Type: application/json
Authorization: Bearer {{auth_token}}

c''

###Create SU on platine pilotage
POST https://api.collecte-enqueteurs.enquetes.recette2.insee.fr/api/survey-units
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[{
  "id": "MBG0003",
  "organizationUnitId": "OU-TEST1",
  "persons": [
    {
      "title": "MISS",
      "firstName": "Elisabeth",
      "lastName": "Dupont",
      "email": "toto@gmail.com",
      "birthdate": 1577833200000,
      "favoriteEmail": true,
      "privileged": true,
      "phoneNumbers": [
        {
          "source": "FISCAL",
          "favorite": true,
          "number": "0101010101"
        },
        {
          "source": "DIRECTORY",
          "favorite": false,
          "number": "0101010102"
        }
      ]
    }
  ],
  "address": {
    "l1": "M. Enzo Dupont",
    "l2": "b",
    "l3": null,
    "l4": "1 TER Rue de la Libération",
    "l5": "c",
    "l6": "54000 Nancy",
    "l7": "France",
    "elevator": false,
    "building": null,
    "floor": null,
    "door": null,
    "staircase": null,
    "cityPriorityDistrict": false
  },
  "priority": true,
  "campaign": "AAA2022X02",
  "sampleIdentifiers": {
    "bs": 0,
    "ec": "0",
    "le": 0,
    "noi": 4,
    "numfa": 1,
    "rges": 10,
    "ssech": 2,
    "nolog": 1,
    "nole": 0,
    "autre": "",
    "nograp": ""
  },
  "states": [
    {
      "date": 0,
      "type": "VIN"
    }
  ]
}]
###



