### GET TOKEN
POST https://auth.insee.test/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
  client.global.set("auth_token", response.body.access_token);
  client.log("TOKEN = "+client.global.get("auth_token"));
    client.log("RESPONSE = "+client.global);


%}


###Create process
POST http://localhost:8080/flowable-rest/runtime/process-instances
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "processDefinitionKey":"simpleProcess",
  "businessKey":"myBusinessKey",
  "returnVariables":false,
  "variables": [
  ]
}


### Récupération de la 1ere tache
GET http://localhost:8080/flowable-rest/runtime/tasks
Content-Type: application/json
Authorization: Bearer {{auth_token}}


> {%
client.log("contentType="+response.contentType.mimeType);
client.log("body="+JSON.stringify(response.body));
client.log("data="+JSON.stringify(response.body["data"][0]["id"]));
    client.test("Nb Tasks==1", function() {
        client.assert(response.body["data"].length === 1, "Pas le bon nb de tasks attendu==1 - trouvees="+response.body["data"].length);
    });
client.global.set("taskId", response.body["data"][0]["id"]);

%}

#######Envoi du contexte
POST http://localhost:8080/flowable-rest/protools-process/upload-context?taskID={{taskId}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="protoools-context.json"

< ./protools-context.json

--WebAppBoundary--

###

