package fr.insee.protools.backend.service.platine.pilotage.metadata;

import lombok.Getter;

@Getter
public enum PeriodEnum {

    A00(PeriodicityEnum.A, "annual"),
    X00(PeriodicityEnum.X, "pluriannual"),
    X01(PeriodicityEnum.X, "pluriannual"),
    X02(PeriodicityEnum.X, "pluriannual"),
    X03(PeriodicityEnum.X, "pluriannual"),
    X04(PeriodicityEnum.X, "pluriannual"),
    X05(PeriodicityEnum.X, "pluriannual"),
    X06(PeriodicityEnum.X, "pluriannual"),
    X07(PeriodicityEnum.X, "pluriannual"),
    X08(PeriodicityEnum.X, "pluriannual"),
    X09(PeriodicityEnum.X, "pluriannual"),
    X10(PeriodicityEnum.X, "pluriannual"),
    X11(PeriodicityEnum.X, "pluriannual"),
    X12(PeriodicityEnum.X, "pluriannual"),
    X13(PeriodicityEnum.X, "pluriannual"),
    X14(PeriodicityEnum.X, "pluriannual"),
    X15(PeriodicityEnum.X, "pluriannual"),
    X16(PeriodicityEnum.X, "pluriannual"),
    X17(PeriodicityEnum.X, "pluriannual"),
    X18(PeriodicityEnum.X, "pluriannual"),
    X19(PeriodicityEnum.X, "pluriannual"),
    X20(PeriodicityEnum.X, "pluriannual"),
    X21(PeriodicityEnum.X, "pluriannual"),
    X22(PeriodicityEnum.X, "pluriannual"),
    X23(PeriodicityEnum.X, "pluriannual"),
    X24(PeriodicityEnum.X, "pluriannual"),
    X25(PeriodicityEnum.X, "pluriannual"),
    X26(PeriodicityEnum.X, "pluriannual"),
    X27(PeriodicityEnum.X, "pluriannual"),
    X28(PeriodicityEnum.X, "pluriannual"),
    X29(PeriodicityEnum.X, "pluriannual"),
    X30(PeriodicityEnum.X, "pluriannual"),
    X31(PeriodicityEnum.X, "pluriannual"),
    X32(PeriodicityEnum.X, "pluriannual"),
    X33(PeriodicityEnum.X, "pluriannual"),
    X34(PeriodicityEnum.X, "pluriannual"),
    X35(PeriodicityEnum.X, "pluriannual"),
    X36(PeriodicityEnum.X, "pluriannual"),
    X37(PeriodicityEnum.X, "pluriannual"),
    X38(PeriodicityEnum.X, "pluriannual"),
    X39(PeriodicityEnum.X, "pluriannual"),
    X40(PeriodicityEnum.X, "pluriannual"),
    X41(PeriodicityEnum.X, "pluriannual"),
    X42(PeriodicityEnum.X, "pluriannual"),
    X43(PeriodicityEnum.X, "pluriannual"),
    X44(PeriodicityEnum.X, "pluriannual"),
    X45(PeriodicityEnum.X, "pluriannual"),
    X46(PeriodicityEnum.X, "pluriannual"),
    X47(PeriodicityEnum.X, "pluriannual"),
    X48(PeriodicityEnum.X, "pluriannual"),
    X49(PeriodicityEnum.X, "pluriannual"),
    X50(PeriodicityEnum.X, "pluriannual"),
    X51(PeriodicityEnum.X, "pluriannual"),
    X52(PeriodicityEnum.X, "pluriannual"),
    X53(PeriodicityEnum.X, "pluriannual"),
    X54(PeriodicityEnum.X, "pluriannual"),
    X55(PeriodicityEnum.X, "pluriannual"),
    X56(PeriodicityEnum.X, "pluriannual"),
    X57(PeriodicityEnum.X, "pluriannual"),
    X58(PeriodicityEnum.X, "pluriannual"),
    X59(PeriodicityEnum.X, "pluriannual"),
    X60(PeriodicityEnum.X, "pluriannual"),
    X61(PeriodicityEnum.X, "pluriannual"),
    X62(PeriodicityEnum.X, "pluriannual"),
    X63(PeriodicityEnum.X, "pluriannual"),
    X64(PeriodicityEnum.X, "pluriannual"),
    X65(PeriodicityEnum.X, "pluriannual"),
    X66(PeriodicityEnum.X, "pluriannual"),
    X67(PeriodicityEnum.X, "pluriannual"),
    X68(PeriodicityEnum.X, "pluriannual"),
    X69(PeriodicityEnum.X, "pluriannual"),
    X70(PeriodicityEnum.X, "pluriannual"),
    X71(PeriodicityEnum.X, "pluriannual"),
    X72(PeriodicityEnum.X, "pluriannual"),
    X73(PeriodicityEnum.X, "pluriannual"),
    X74(PeriodicityEnum.X, "pluriannual"),
    X75(PeriodicityEnum.X, "pluriannual"),
    X76(PeriodicityEnum.X, "pluriannual"),
    X77(PeriodicityEnum.X, "pluriannual"),
    X78(PeriodicityEnum.X, "pluriannual"),
    X79(PeriodicityEnum.X, "pluriannual"),
    X80(PeriodicityEnum.X, "pluriannual"),
    X81(PeriodicityEnum.X, "pluriannual"),
    X82(PeriodicityEnum.X, "pluriannual"),
    X83(PeriodicityEnum.X, "pluriannual"),
    X84(PeriodicityEnum.X, "pluriannual"),
    X85(PeriodicityEnum.X, "pluriannual"),
    X86(PeriodicityEnum.X, "pluriannual"),
    X87(PeriodicityEnum.X, "pluriannual"),
    X88(PeriodicityEnum.X, "pluriannual"),
    X89(PeriodicityEnum.X, "pluriannual"),
    X90(PeriodicityEnum.X, "pluriannual"),
    X91(PeriodicityEnum.X, "pluriannual"),
    X92(PeriodicityEnum.X, "pluriannual"),
    X93(PeriodicityEnum.X, "pluriannual"),
    X94(PeriodicityEnum.X, "pluriannual"),
    X95(PeriodicityEnum.X, "pluriannual"),
    X96(PeriodicityEnum.X, "pluriannual"),
    X97(PeriodicityEnum.X, "pluriannual"),
    X98(PeriodicityEnum.X, "pluriannual"),
    X99(PeriodicityEnum.X, "pluriannual"),
    S01(PeriodicityEnum.S, "1st semester"),
    S02(PeriodicityEnum.S, "2nd semester"),
    T01(PeriodicityEnum.T, "1st trimester"),
    T02(PeriodicityEnum.T, "2nd trimester"),
    T03(PeriodicityEnum.T, "3rd trimester"),
    T04(PeriodicityEnum.T, "4th trimester"),
    M01(PeriodicityEnum.M, "january"),
    M02(PeriodicityEnum.M, "february"),
    M03(PeriodicityEnum.M, "march"),
    M04(PeriodicityEnum.M, "april"),
    M05(PeriodicityEnum.M, "may"),
    M06(PeriodicityEnum.M, "june"),
    M07(PeriodicityEnum.M, "july"),
    M08(PeriodicityEnum.M, "august"),
    M09(PeriodicityEnum.M, "september"),
    M10(PeriodicityEnum.M, "october"),
    M11(PeriodicityEnum.M, "november"),
    M12(PeriodicityEnum.M, "december"),
    B01(PeriodicityEnum.B, "1st bimester"),
    B02(PeriodicityEnum.B, "2nd bimester"),
    B03(PeriodicityEnum.B, "3rd bimester"),
    B04(PeriodicityEnum.B, "4th bimester"),
    B05(PeriodicityEnum.B, "5th bimester"),
    B06(PeriodicityEnum.B, "6th bimester"),

    ;

    PeriodEnum(PeriodicityEnum period, String value) {
        this.value = value;
        this.period = period;
    }

    final PeriodicityEnum period;

    final String value;

}